name = "DifferentialGames"
uuid = "497f78f8-f326-11f0-3aad-a3ebf6911431"
authors = ["BennetOutland <bennet.outland@pm.me> and contributors"]
version = "0.1.0"

[deps]
DifferentialGamesBase = "a9dd1e63-b4ad-4579-bca8-3a609f3d87b9"
DifferentialGamesBaseSolvers = "b83b0c57-42fa-43ab-a182-d5be40f43772"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DifferentialGamesBase = "1.0.0"
DifferentialGamesBaseSolvers = "1.0.0"
Reexport = "1.2.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
